name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PACKAGE_NAME: Zinc
  # XCODEBUILD_WORKSPACE: UtilityBelt.xcworkspace
  # XCODEBUILD_SCHEME: UtilityBelt
  DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
  DEPLOY_DIRECTORY: deploy

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          bundle install
          brew install swiftformat
      - name: Run Danger
        run: sh ./scripts/danger_lint.sh
  spm:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: sh ./scripts/swift_build.sh
      - name: Upload Step Output
        uses: actions/upload-artifact@v1
        with:
          name: "${{ matrix.os }} Output"
          path: ${{ env.DEPLOY_DIRECTORY }}
