name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEPLOY_DIRECTORY: deploy
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          bundle install
          brew install swiftformat
      - name: Run Danger
        run: sh ./scripts/danger_lint.sh
  spm:
    name: SPM (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: sh ./scripts/swift_build.sh
      - name: Upload Step Output
        uses: actions/upload-artifact@v1
        with:
          name: SPM Output
          path: ${{ env.DEPLOY_DIRECTORY }}
